### ISSUE TITLE
Install custom Github App redirect show error.

### ISSUE THREAD

**Issue by coderkhalide** [Dokploy/dokploy#12]
I was installing the custom app i created on my personal account by following this [Installing your own GitHub App](https://docs.github.com/en/apps/using-github-apps/installing-your-own-github-app#installing-your-own-github-app) (Note: I think this link should be added on Docs)

After install it redirected to https://[myserver]/api/redirect?code=[code]&installation_id=50229813&setup_action=install

and the ui showed `Internal Server Error`

I checked the log:
```bash
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at p (/app/.next/server/pages/api/redirect.js:1:1492)
    at /app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16638
    at /app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/app/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
```

<img width="398" alt="image" src="https://github.com/Dokploy/dokploy/assets/72712376/3b73f971-9141-41ed-836e-1754ca272605">

**Comment by coderkhalide** [comment]
Solved it.

**Comment by coderkhalide** [comment]
Solve Process 

https://www.loom.com/share/8e97e897b4074fa98b61bd1d7b42e653
