### ISSUE TITLE
Dokploy BE dies after a few deploys

### ISSUE THREAD

**Issue by max-degterev** [Dokploy/dokploy#455]
### To Reproduce

Idk run my deploys i guess

### Current vs. Expected behavior

no crash

### Provide environment information

```bash
last ubuntu on hetzner
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

```dokploy.1.9iig3pomqd5h@staging-bldry    | Build dockerfile: ✅
dokploy.1.9iig3pomqd5h@staging-bldry    | Build dockerfile: ✅
dokploy.1.9iig3pomqd5h@staging-bldry    | {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P02',
dokploy.1.9iig3pomqd5h@staging-bldry    |   message: 'terminating connection because of crash of another server process',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   hint: 'In a moment you should be able to reconnect to the database and repeat your command.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postgres.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2938',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'quickdie'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P02',
dokploy.1.9iig3pomqd5h@staging-bldry    |   message: 'terminating connection because of crash of another server process',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   hint: 'In a moment you should be able to reconnect to the database and repeat your command.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postgres.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2938',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'quickdie'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P02',
dokploy.1.9iig3pomqd5h@staging-bldry    |   message: 'terminating connection because of crash of another server process',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   hint: 'In a moment you should be able to reconnect to the database and repeat your command.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postgres.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2938',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'quickdie'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P02',
dokploy.1.9iig3pomqd5h@staging-bldry    |   message: 'terminating connection because of crash of another server process',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   hint: 'In a moment you should be able to reconnect to the database and repeat your command.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postgres.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2938',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'quickdie'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P02',
dokploy.1.9iig3pomqd5h@staging-bldry    |   message: 'terminating connection because of crash of another server process',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   hint: 'In a moment you should be able to reconnect to the database and repeat your command.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postgres.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2938',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'quickdie'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P02',
dokploy.1.9iig3pomqd5h@staging-bldry    |   message: 'terminating connection because of crash of another server process',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   hint: 'In a moment you should be able to reconnect to the database and repeat your command.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postgres.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2938',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'quickdie'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'WARNING',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P02',
dokploy.1.9iig3pomqd5h@staging-bldry    |   message: 'terminating connection because of crash of another server process',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   hint: 'In a moment you should be able to reconnect to the database and repeat your command.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postgres.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2938',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'quickdie'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | PostgresError: the database system is not yet accepting connections
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'Consistent recovery state has not been yet reached.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2340',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | PostgresError: the database system is not yet accepting connections
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'Consistent recovery state has not been yet reached.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2340',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | undefined undefined
dokploy.1.9iig3pomqd5h@staging-bldry    |  ⨯ PostgresError: the database system is in recovery mode
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2356',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | undefined undefined
dokploy.1.9iig3pomqd5h@staging-bldry    |  ⨯ PostgresError: the database system is not yet accepting connections
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'Consistent recovery state has not been yet reached.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2340',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | undefined undefined
dokploy.1.9iig3pomqd5h@staging-bldry    |  ⨯ PostgresError: the database system is not yet accepting connections
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'Consistent recovery state has not been yet reached.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2340',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | undefined undefined
dokploy.1.9iig3pomqd5h@staging-bldry    |  ⨯ PostgresError: the database system is not yet accepting connections
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'Consistent recovery state has not been yet reached.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2340',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | undefined undefined
dokploy.1.9iig3pomqd5h@staging-bldry    |  ⨯ PostgresError: the database system is not yet accepting connections
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'Consistent recovery state has not been yet reached.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2340',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | undefined undefined
dokploy.1.9iig3pomqd5h@staging-bldry    |  ⨯ PostgresError: the database system is not yet accepting connections
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   detail: 'Consistent recovery state has not been yet reached.',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2340',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }
dokploy.1.9iig3pomqd5h@staging-bldry    | undefined undefined
dokploy.1.9iig3pomqd5h@staging-bldry    |  ⨯ PostgresError: the database system is in recovery mode
dokploy.1.9iig3pomqd5h@staging-bldry    |     at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at handle (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.data (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Socket.emit (node:events:517:28)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at addChunk (node:internal/streams/readable:368:12)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at readableAddChunk (node:internal/streams/readable:341:9)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at Readable.push (node:internal/streams/readable:278:10)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
dokploy.1.9iig3pomqd5h@staging-bldry    |     at TCP.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity_local: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   severity: 'FATAL',
dokploy.1.9iig3pomqd5h@staging-bldry    |   code: '57P03',
dokploy.1.9iig3pomqd5h@staging-bldry    |   file: 'postmaster.c',
dokploy.1.9iig3pomqd5h@staging-bldry    |   line: '2356',
dokploy.1.9iig3pomqd5h@staging-bldry    |   routine: 'ProcessStartupPacket'
dokploy.1.9iig3pomqd5h@staging-bldry    | }```

log

**Comment by max-degterev** [comment]
OOM
