### ISSUE TITLE
Connection problem between dokploy and components on LXC 

### ISSUE THREAD

**Issue by LeslieLeung** [Dokploy/dokploy#65]
I am trying to install dokploy on a Proxmox VE LXC. The dokploy and all its components can start without any problem, but when I follow the link in the end of the installation, the page won't load and get a `500 Internal Error`.

Upon checking the log of the dokploy container, clearly it can't talk to the redis and postgres. Here is the log:

```
 ⨯ Error: write CONNECT_TIMEOUT dokploy-postgres:5432
    at connectTimedOut (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:257:20)
    at Timeout.done [as _onTimeout] (file:///app/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:1033:8)
    at listOnTimeout (node:internal/timers:571:11)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'CONNECT_TIMEOUT',
  errno: 'CONNECT_TIMEOUT',
  address: 'dokploy-postgres',
  port: 5432
}
Error: connect ETIMEDOUT
    at Socket.<anonymous> (/app/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:631:28)
    at Socket.emit (node:events:517:28)
    at Socket._onTimeout (node:net:598:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
```

I can confirm traefik, redis, postgres and the dokploy containers are up and running:
```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                                                                                                                 NAMES
6572e6aa7b00   redis:7                  "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes   6379/tcp                                                                                                              dokploy-redis.1.kjx49cyo7r0y3qxm5qxqkhy79
83ccc4c98f5c   traefik:v2.5             "/entrypoint.sh trae…"   16 minutes ago   Up 16 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   dokploy-traefik.1.7v5t1a7m88udld82mpwdr1d97
f1c94cf7c034   postgres:16              "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes   5432/tcp                                                                                                              dokploy-postgres.1.uajqlmpkmikos2xx670q6iwrh
233a0b9e1746   dokploy/dokploy:latest   "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                             dokploy.1.pk9dz8qwonpmc6wi0nq8be711
```

Here is my installation process:
- Create a clean Ubuntu 22.04 LXC with `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/ubuntu.sh)"`
- Run the script `curl -sSL https://dokploy.com/install.sh | sh`

**Comment by Siumauricio** [comment]
This is a proxmox problem, not dokploy, many people have tried to use it but you have to make certain configurations regarding routes and ips, I can't give you an exact solution since I have never used proxmox, on discord several people have solved this problem

If you can tell me where I can rent a server with Proxmox to try it, I would be happy to make a guide.

**Comment by LeslieLeung** [comment]
I've joined the discord server and read some of the chats before about Proxmox. So it appears that dokploy on a VM works  but not LXC, probably docker network problem. I believe there is a solution to this. LXC is better than VM because it's lighter.

> If you can tell me where I can rent a server with Proxmox to try it, I would be happy to make a guide.

About this, I found some websites on the Proxmox Hosting Partners, see [here](https://www.proxmox.com/en/partners/all/filter/partners/partner/partner-type-filter/partner-type/hosting-partner). But you can run a Proxmox server with really cheap hardware(it's basically Debian with a management software for qemu). I think deploying your own Proxmox server would be a better choice.

A guide to run dokploy on Proxmox VE would be great because a) dokploy is really a great work and very suitable for self hosting, b) Proxmox VE is a popular choice for homeservers.

**Comment by Mr1Blaze** [comment]
Which ubuntu 20.04 are you use? Because in my case it's work very well. How was created and configured CT on proxmox?

**Comment by LeslieLeung** [comment]
It's Ubuntu 22.04 and privileged.
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

Here is the `/etc/pve/lxc/x.conf`:
```
arch: amd64
cores: 2
features: nesting=1
hostname: ubuntu
memory: 4096
net0: name=eth0,bridge=vmbr0,gw=xxx,hwaddr=xxx,ip=xxx/24,type=veth
onboot: 1
ostype: ubuntu
rootfs: local-lvm:vm-101-disk-0,size=128G
swap: 512
tags: proxmox-helper-scripts
lxc.cgroup2.devices.allow: a
lxc.cap.drop: 
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyUSB1       dev/ttyUSB1       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
```

**Comment by Mr1Blaze** [comment]
Looks good. But I recommend to deploy on Virtual Machine in Proxmox VE. On LXC will be so slower

**Comment by Siumauricio** [comment]
Since this is a Proxmox Issue, we can close this for now, we recommend to use a normal VPS providers.

**Comment by aloasut** [comment]
solution: 
install script:

```
docker service create \
.....
--endpoint-mode dnsrr \
....
```

use dnsrr can fix the connection time out problem only occuring under lxc.

**Comment by felipemarques** [comment]
> solution: install script:
> 
> ```
> docker service create \
> .....
> --endpoint-mode dnsrr \
> ....
> ```
> 
> use dnsrr can fix the connection time out problem only occuring under lxc.

You are the best @aloasut !!! worked smoothly!


here is the script updated:

```
#!/bin/bash
install_dokploy() {
    if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root" >&2
        exit 1
    fi

    # check if is Mac OS
    if [ "$(uname)" = "Darwin" ]; then
        echo "This script must be run on Linux" >&2
        exit 1
    fi

    # check if is running inside a container
    if [ -f /.dockerenv ]; then
        echo "This script must be run on Linux" >&2
        exit 1
    fi

    # check if something is running on port 80
    if ss -tulnp | grep ':80 ' >/dev/null; then
        echo "Error: something is already running on port 80" >&2
        exit 1
    fi

    # check if something is running on port 443
    if ss -tulnp | grep ':443 ' >/dev/null; then
        echo "Error: something is already running on port 443" >&2
        exit 1
    fi

    command_exists() {
      command -v "$@" > /dev/null 2>&1
    }

    if command_exists docker; then
      echo "Docker already installed"
    else
      curl -sSL https://get.docker.com | sh
    fi

    docker swarm leave --force 2>/dev/null

    get_ip() {
        local ip=""
        
        # Try IPv4 first
        # First attempt: ifconfig.io
        ip=$(curl -4s --connect-timeout 5 https://ifconfig.io 2>/dev/null)
        
        # Second attempt: icanhazip.com
        if [ -z "$ip" ]; then
            ip=$(curl -4s --connect-timeout 5 https://icanhazip.com 2>/dev/null)
        fi
        
        # Third attempt: ipecho.net
        if [ -z "$ip" ]; then
            ip=$(curl -4s --connect-timeout 5 https://ipecho.net/plain 2>/dev/null)
        fi

        # If no IPv4, try IPv6
        if [ -z "$ip" ]; then
            # Try IPv6 with ifconfig.io
            ip=$(curl -6s --connect-timeout 5 https://ifconfig.io 2>/dev/null)
            
            # Try IPv6 with icanhazip.com
            if [ -z "$ip" ]; then
                ip=$(curl -6s --connect-timeout 5 https://icanhazip.com 2>/dev/null)
            fi
            
            # Try IPv6 with ipecho.net
            if [ -z "$ip" ]; then
                ip=$(curl -6s --connect-timeout 5 https://ipecho.net/plain 2>/dev/null)
            fi
        fi

        if [ -z "$ip" ]; then
            echo "Error: Could not determine server IP address automatically (neither IPv4 nor IPv6)." >&2
            echo "Please set the ADVERTISE_ADDR environment variable manually." >&2
            echo "Example: export ADVERTISE_ADDR=<your-server-ip>" >&2
            exit 1
        fi

        echo "$ip"
    }

    get_private_ip() {
        ip addr show | grep -E "inet (192\.168\.|10\.|172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.)" | head -n1 | awk '{print $2}' | cut -d/ -f1
    }

    advertise_addr="${ADVERTISE_ADDR:-$(get_private_ip)}"

    if [ -z "$advertise_addr" ]; then
        echo "ERROR: We couldn't find a private IP address."
        echo "Please set the ADVERTISE_ADDR environment variable manually."
        echo "Example: export ADVERTISE_ADDR=192.168.1.100"
        exit 1
    fi
    echo "Using advertise address: $advertise_addr"

    docker swarm init --advertise-addr $advertise_addr
    
     if [ $? -ne 0 ]; then
        echo "Error: Failed to initialize Docker Swarm" >&2
        exit 1
    fi

    echo "Swarm initialized"

    docker network rm -f dokploy-network 2>/dev/null
    docker network create --driver overlay --attachable dokploy-network

    echo "Network created"

    mkdir -p /etc/dokploy

    chmod 777 /etc/dokploy

    docker service create \
    --name dokploy-postgres \
    --constraint 'node.role==manager' \
    --network dokploy-network \
    --endpoint-mode dnsrr \
    --env POSTGRES_USER=dokploy \
    --env POSTGRES_DB=dokploy \
    --env POSTGRES_PASSWORD=amukds4wi9001583845717ad2 \
    --mount type=volume,source=dokploy-postgres-database,target=/var/lib/postgresql/data \
    postgres:16

    docker service create \
    --name dokploy-redis \
    --constraint 'node.role==manager' \
    --endpoint-mode dnsrr \
    --network dokploy-network \
    --mount type=volume,source=redis-data-volume,target=/data \
    redis:7

    # Installation
    docker service create \
      --name dokploy \
      --replicas 1 \
      --endpoint-mode dnsrr \
      --network dokploy-network \
      --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
      --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
      --mount type=volume,source=dokploy-docker-config,target=/root/.docker \
      --publish published=3000,target=3000,mode=host \
      --update-parallelism 1 \
      --update-order stop-first \
      --constraint 'node.role == manager' \
      -e ADVERTISE_ADDR=$advertise_addr \
      dokploy/dokploy:latest

    sleep 4

    docker run -d \
        --name dokploy-traefik \
        --restart always \
        -v /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml \
        -v /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -p 80:80/tcp \
        -p 443:443/tcp \
        -p 443:443/udp \
        traefik:v3.1.2
    
    docker network connect dokploy-network dokploy-traefik


    # Optional: Use docker service create instead of docker run
    #   docker service create \
    #     --name dokploy-traefik \
    #     --constraint 'node.role==manager' \
    #     --network dokploy-network \
    #     --mount type=bind,source=/etc/dokploy/traefik/traefik.yml,target=/etc/traefik/traefik.yml \
    #     --mount type=bind,source=/etc/dokploy/traefik/dynamic,target=/etc/dokploy/traefik/dynamic \
    #     --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    #     --publish mode=host,published=443,target=443 \
    #     --publish mode=host,published=80,target=80 \
    #     --publish mode=host,published=443,target=443,protocol=udp \
    #     traefik:v3.1.2

    GREEN="\033[0;32m"
    YELLOW="\033[1;33m"
    BLUE="\033[0;34m"
    NC="\033[0m" # No Color

    format_ip_for_url() {
        local ip="$1"
        if echo "$ip" | grep -q ':'; then
            # IPv6
            echo "[${ip}]"
        else
            # IPv4
            echo "${ip}"
        fi
    }

    public_ip="${ADVERTISE_ADDR:-$(get_ip)}"
    formatted_addr=$(format_ip_for_url "$public_ip")
    echo ""
    printf "${GREEN}Congratulations, Dokploy is installed!${NC}\n"
    printf "${BLUE}Wait 15 seconds for the server to start${NC}\n"
    printf "${YELLOW}Please go to http://${formatted_addr}:3000${NC}\n\n"
}

update_dokploy() {
    echo "Updating Dokploy..."
    
    # Pull the latest image
    docker pull dokploy/dokploy:latest

    # Update the service
    docker service update --image dokploy/dokploy:latest dokploy

    echo "Dokploy has been updated to the latest version."
}

# Main script execution
if [ "$1" = "update" ]; then
    update_dokploy
else
    install_dokploy
fi
```

**Comment by kyesil** [comment]
@aloasut 
> solution: install script:
> 
> ```
> docker service create \
> .....
> --endpoint-mode dnsrr \
> ....
> ```
> 
> use dnsrr can fix the connection time out problem only occuring under lxc.

its working thanks. 

@Siumauricio 
> Since this is a Proxmox Issue, we can close this for now, we recommend to use a normal VPS providers.

easy to say proxmox problem.  we need reason.

**Comment by haouarihk** [comment]
# WARNING THIS IS A CHATGPT ANSWER

Using --endpoint-mode dnsrr can cause some side effects.


By default, **Proxmox LXC containers are quite restricted**, and these restrictions break Docker’s networking features like:

* Overlay networks
* `--mode vip` load balancing
* Internal DNS resolution
* Ingress routing mesh

---

## :white_check_mark: Solution: Run Docker in an Unprivileged LXC with Network Access Fixed

### Step 1: Enable Required Kernel Features in the LXC Container

You need to adjust the container config to enable:

* `iptables` (or more specifically `xtables`)
* `overlay` kernel module
* Full `net_admin` capability

Edit the container config file on the **Proxmox host**:

```bash
nano /etc/pve/lxc/<CTID>.conf
```

Add or ensure the following:

```ini
# Required for Docker overlay networking
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.cap.drop:

# Allow iptables, overlay, etc.
lxc.mount.auto: proc:rw sys:rw
lxc.net.0.type: veth
lxc.net.0.flags: up
lxc.apparmor.allow_nesting: 1
features: keyctl=1,nesting=1,fuse=1
```

### Step 2: Ensure the Host Kernel Modules Are Loaded

On the Proxmox host:

```bash
modprobe overlay
modprobe br_netfilter
```

You may want to ensure these modules load at boot:

```bash
echo overlay >> /etc/modules
echo br_netfilter >> /etc/modules
```

---

### Step 3: Inside the LXC Container

Install Docker as usual, and check that `iptables` and `overlay` are working:

```bash
docker info | grep -i overlay
docker info | grep -i iptables
```

You should see no errors or warnings about networking.

---

### Step 4: Use Default `--mode vip` Networking in Dokploy

Once the container has proper networking capabilities, you can **use the default Swarm networking mode (`--mode vip`)**.

Example:

```bash
dokploy service create \
  --name myservice \
  --replicas 3 \
  myimage
```

Swarm's internal DNS and VIP-based load balancer will now work properly — **no need for `--mode dnsrr`**.

---

## :test_tube: Bonus: Troubleshooting Tips

* `docker network create -d overlay testnet`
  → Should succeed without error.

* `docker service create --network testnet ...`
  → Should work and load balance across replicas.

* `ping myservice` or `curl myservice:port`
  → Should resolve and connect correctly across tasks.

---

## :warning: Caveats

* **LXC is less Docker-friendly than full VMs**. If you’re deploying Docker Swarm in production, consider using **KVM VMs on Proxmox** instead for full isolation and compatibility.
* Still, for development, test clusters, or light production use — **a properly configured LXC** is totally usable.

---

**Comment by kipavy** [comment]
Hi, I think this issue should be re-opened or a fix to the script should be pushed, I just tried to install dokploy via its script on a fresh debian docker LXC, it couldn't connect to redis on 10.0.1.5 cause it was always set on 10.0.1.6 automatically. So I tried to uninstall following the docs https://docs.dokploy.com/docs/core/uninstall but since traefik is started using docker run (unlike other services that are using docker service) the uninstall command didnt work, so I switched traefik to a service like suggested the comment in the install script and now I can access dokploy on :3000, anyways heres the script (I've just replace the traefik part), if some dokploy dev sees this, please update the script, this is unacceptable

```bash
#!/bin/bash
install_dokploy() {
    if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root" >&2
        exit 1
    fi

    # check if is Mac OS
    if [ "$(uname)" = "Darwin" ]; then
        echo "This script must be run on Linux" >&2
        exit 1
    fi

    # check if is running inside a container
    if [ -f /.dockerenv ]; then
        echo "This script must be run on Linux" >&2
        exit 1
    fi

    # check if something is running on port 80
    if ss -tulnp | grep ':80 ' >/dev/null; then
        echo "Error: something is already running on port 80" >&2
        exit 1
    fi

    # check if something is running on port 443
    if ss -tulnp | grep ':443 ' >/dev/null; then
        echo "Error: something is already running on port 443" >&2
        exit 1
    fi

    command_exists() {
      command -v "$@" > /dev/null 2>&1
    }

    if command_exists docker; then
      echo "Docker already installed"
    else
      curl -sSL https://get.docker.com | sh
    fi

    docker swarm leave --force 2>/dev/null

    get_ip() {
        local ip=""
        
        # Try IPv4 first
        # First attempt: ifconfig.io
        ip=$(curl -4s --connect-timeout 5 https://ifconfig.io 2>/dev/null)
        
        # Second attempt: icanhazip.com
        if [ -z "$ip" ]; then
            ip=$(curl -4s --connect-timeout 5 https://icanhazip.com 2>/dev/null)
        fi
        
        # Third attempt: ipecho.net
        if [ -z "$ip" ]; then
            ip=$(curl -4s --connect-timeout 5 https://ipecho.net/plain 2>/dev/null)
        fi

        # If no IPv4, try IPv6
        if [ -z "$ip" ]; then
            # Try IPv6 with ifconfig.io
            ip=$(curl -6s --connect-timeout 5 https://ifconfig.io 2>/dev/null)
            
            # Try IPv6 with icanhazip.com
            if [ -z "$ip" ]; then
                ip=$(curl -6s --connect-timeout 5 https://icanhazip.com 2>/dev/null)
            fi
            
            # Try IPv6 with ipecho.net
            if [ -z "$ip" ]; then
                ip=$(curl -6s --connect-timeout 5 https://ipecho.net/plain 2>/dev/null)
            fi
        fi

        if [ -z "$ip" ]; then
            echo "Error: Could not determine server IP address automatically (neither IPv4 nor IPv6)." >&2
            echo "Please set the ADVERTISE_ADDR environment variable manually." >&2
            echo "Example: export ADVERTISE_ADDR=<your-server-ip>" >&2
            exit 1
        fi

        echo "$ip"
    }

    get_private_ip() {
        ip addr show | grep -E "inet (192\.168\.|10\.|172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.)" | head -n1 | awk '{print $2}' | cut -d/ -f1
    }

    advertise_addr="${ADVERTISE_ADDR:-$(get_private_ip)}"

    if [ -z "$advertise_addr" ]; then
        echo "ERROR: We couldn't find a private IP address."
        echo "Please set the ADVERTISE_ADDR environment variable manually."
        echo "Example: export ADVERTISE_ADDR=192.168.1.100"
        exit 1
    fi
    echo "Using advertise address: $advertise_addr"

    docker swarm init --advertise-addr $advertise_addr
    
     if [ $? -ne 0 ]; then
        echo "Error: Failed to initialize Docker Swarm" >&2
        exit 1
    fi

    echo "Swarm initialized"

    docker network rm -f dokploy-network 2>/dev/null
    docker network create --driver overlay --attachable dokploy-network

    echo "Network created"

    mkdir -p /etc/dokploy

    chmod 777 /etc/dokploy

    docker service create \
    --name dokploy-postgres \
    --constraint 'node.role==manager' \
    --network dokploy-network \
    --endpoint-mode dnsrr \
    --env POSTGRES_USER=dokploy \
    --env POSTGRES_DB=dokploy \
    --env POSTGRES_PASSWORD=amukds4wi9001583845717ad2 \
    --mount type=volume,source=dokploy-postgres-database,target=/var/lib/postgresql/data \
    postgres:16

    docker service create \
    --name dokploy-redis \
    --constraint 'node.role==manager' \
    --endpoint-mode dnsrr \
    --network dokploy-network \
    --mount type=volume,source=redis-data-volume,target=/data \
    redis:7

    # Installation
    docker service create \
      --name dokploy \
      --replicas 1 \
      --endpoint-mode dnsrr \
      --network dokploy-network \
      --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
      --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
      --mount type=volume,source=dokploy-docker-config,target=/root/.docker \
      --publish published=3000,target=3000,mode=host \
      --update-parallelism 1 \
      --update-order stop-first \
      --constraint 'node.role == manager' \
      -e ADVERTISE_ADDR=$advertise_addr \
      dokploy/dokploy:latest

    sleep 4

    # docker run -d \
    #     --name dokploy-traefik \
    #     --restart always \
    #     -v /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml \
    #     -v /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic \
    #     -v /var/run/docker.sock:/var/run/docker.sock \
    #     -p 80:80/tcp \
    #     -p 443:443/tcp \
    #     -p 443:443/udp \
    #     traefik:v3.1.2

    # Optional: Use docker service create instead of docker run
    docker service create \
        --name dokploy-traefik \
        --constraint 'node.role==manager' \
        --network dokploy-network \
        --mount type=bind,source=/etc/dokploy/traefik/traefik.yml,target=/etc/traefik/traefik.yml \
        --mount type=bind,source=/etc/dokploy/traefik/dynamic,target=/etc/dokploy/traefik/dynamic \
        --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
        --publish mode=host,published=443,target=443 \
        --publish mode=host,published=80,target=80 \
        --publish mode=host,published=443,target=443,protocol=udp \
        traefik:v3.1.2
    
    docker network connect dokploy-network dokploy-traefik


    GREEN="\033[0;32m"
    YELLOW="\033[1;33m"
    BLUE="\033[0;34m"
    NC="\033[0m" # No Color

    format_ip_for_url() {
        local ip="$1"
        if echo "$ip" | grep -q ':'; then
            # IPv6
            echo "[${ip}]"
        else
            # IPv4
            echo "${ip}"
        fi
    }

    public_ip="${ADVERTISE_ADDR:-$(get_ip)}"
    formatted_addr=$(format_ip_for_url "$public_ip")
    echo ""
    printf "${GREEN}Congratulations, Dokploy is installed!${NC}\n"
    printf "${BLUE}Wait 15 seconds for the server to start${NC}\n"
    printf "${YELLOW}Please go to http://${formatted_addr}:3000${NC}\n\n"
}

update_dokploy() {
    echo "Updating Dokploy..."
    
    # Pull the latest image
    docker pull dokploy/dokploy:latest

    # Update the service
    docker service update --image dokploy/dokploy:latest dokploy

    echo "Dokploy has been updated to the latest version."
}

# Main script execution
if [ "$1" = "update" ]; then
    update_dokploy
else
    install_dokploy
fi
```
