### ISSUE TITLE
[GPU support] NVIDIA Container Runtime Not Installed

### ISSUE THREAD

**Issue by mcandylab** [Dokploy/dokploy#816]
### To Reproduce

1. `/etc/docker/daemon.json`:
```
{
    "experimental": true,
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "default-runtime": "nvidia",
    "node-generic-resources": [
        "gpu=GPU-6d83c4e3-32f7-d069-4d88-d384addeebdb",
        "gpu=GPU-0b9d9b4e-082c-7468-3b41-8f26d1949bc5"
    ]
}
```

2. `/etc/nvidia-container-runtime/config.toml`:
```
...
disable-require = false
supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video"
swarm-resource = "DOCKER_RESOURCE_GPU"
...
```

3. `nvidia-smi -L`
```
GPU 0: Tesla T4 (UUID: GPU-6d83c4e3-32f7-d069-4d88-d384addeebdb)
GPU 1: Tesla T4 (UUID: GPU-0b9d9b4e-082c-7468-3b41-8f26d1949bc5)
```

4. `docker info | grep -i runtime`
```
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: nvidia
```

5. `nvidia-container-runtime -v`
```
runc version 1.2.2
commit: v1.2.2-0-g7cb3632
spec: 1.2.0
go: go1.22.9
libseccomp: 2.5.4
```

### Current vs. Expected behavior

-

### Provide environment information

```bash
Debian 12
2 Tesla T4 16GB
```

### Which area(s) are affected? (Select all that apply)

Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

![Снимок экрана 2024-12-05 в 12 13 53](https://github.com/user-attachments/assets/9305e950-a575-4f0c-8d16-f07607104d93)

I cannot activate the GPU because NVIDIA Container Runtime is not installed.

What should I do?

### Will you send a PR to fix it?

No

**Comment by mcandylab** [comment]
If I mount the necessary paths during startup, I encounter a different situation when activating the GPU:

```
docker service create \
  --name dokploy \
  --replicas 1 \
  --network dokploy-network \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/usr/bin/nvidia-container-runtime,target=/usr/bin/nvidia-container-runtime,readonly \
  --mount type=bind,source=/etc/docker/daemon.json,target=/etc/docker/daemon.json,readonly \
  --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
  --mount type=volume,source=dokploy-docker-config,target=/root/.docker \
  --publish published=3000,target=3000,mode=host \
  --update-parallelism 1 \
  --update-order stop-first \
  --constraint 'node.role == manager' \
  --generic-resource "gpu=2" \
  -e ADVERTISE_ADDR=$advertise_addr \
  -e NVIDIA_VISIBLE_DEVICES=all \
  dokploy/dokploy:latest
```
![Снимок экрана 2024-12-05 в 12 37 40](https://github.com/user-attachments/assets/29eb7d00-ccfb-489b-b91e-c35e54018d5b)

```
Command failed: pkexec sh -c ' cp /tmp/docker-daemon-1733391482189.json /etc/docker/daemon.json && mkdir -p /etc/nvidia-container-runtime && sed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml && echo "swarm-resource = \"DOCKER_RESOURCE_GPU\"" >> /etc/nvidia-container-runtime/config.toml && systemctl daemon-reload && systemctl restart docker ' && rm /tmp/docker-daemon-1733391482189.json /bin/sh: 1: pkexec: not found
```

**Comment by Siumauricio** [comment]
#837

**Comment by mcandylab** [comment]
After installing `apt-get install policykit-1` I get a new error:

```
Command failed: pkexec sh -c ' cp /tmp/docker-daemon-1733735705170.json /etc/docker/daemon.json && mkdir -p /etc/nvidia-container-runtime && sed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml && echo "swarm-resource = \"DOCKER_RESOURCE_GPU\"" >> /etc/nvidia-container-runtime/config.toml && systemctl daemon-reload && systemctl restart docker ' && rm /tmp/docker-daemon-1733735705170.json Error getting authority: Error initializing authority: Could not connect: No such file or directory
```

**Comment by wizd** [comment]
```
Swarm GPU Support                     Not Enabled
```

try to enable gpu:

```
Setup failed: Error: Command failed: sudo sh -c '
                        cp /tmp/docker-daemon-1735744066225.json /etc/docker/daemon.json &&
                        mkdir -p /etc/nvidia-container-runtime &&
                        sed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml &&
                        echo "swarm-resource = \"DOCKER_RESOURCE_GPU\"" >> /etc/nvidia-container-runtime/config.toml &&
                        systemctl daemon-reload &&
                        systemctl restart docker
                ' && rm /tmp/docker-daemon-1735744066225.json
/bin/sh: 1: sudo: not found

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    at Process.callbackTrampoline (node:internal/async_hooks:128:17) {
  code: 127,
  killed: false,
  signal: null,
  cmd: "sudo sh -c '\n" +
    '\t\t\tcp /tmp/docker-daemon-1735744066225.json /etc/docker/daemon.json && \n' +
    '\t\t\tmkdir -p /etc/nvidia-container-runtime && \n' +
    '\t\t\tsed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml &&\n' +
    '\t\t\techo "swarm-resource = \\"DOCKER_RESOURCE_GPU\\"" >> /etc/nvidia-container-runtime/config.toml && \n' +
    '\t\t\tsystemctl daemon-reload && \n' +
    '\t\t\tsystemctl restart docker\n' +
    "\t\t' && rm /tmp/docker-daemon-1735744066225.json",
  stdout: '',
  stderr: '/bin/sh: 1: sudo: not found\n'
}
GPU Setup Error: Error: Failed to configure GPU support. Please ensure you have sudo privileges and try again.
    at f (/app/.next/server/chunks/8786.js:656:87)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d (/app/.next/server/chunks/8786.js:649:4782)
    at async /app/.next/server/chunks/500.js:14:81086
    at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:421:30)
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
    at async resolve (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
    at async inputToProcedureCall (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
```

Version: v0.16.1

**Comment by wizd** [comment]
> > ```
> > Swarm GPU Support                     Not Enabled
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > try to enable gpu:
> > ```
> > Setup failed: Error: Command failed: sudo sh -c '
> >                         cp /tmp/docker-daemon-1735744066225.json /etc/docker/daemon.json &&
> >                         mkdir -p /etc/nvidia-container-runtime &&
> >                         sed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml &&
> >                         echo "swarm-resource = \"DOCKER_RESOURCE_GPU\"" >> /etc/nvidia-container-runtime/config.toml &&
> >                         systemctl daemon-reload &&
> >                         systemctl restart docker
> >                 ' && rm /tmp/docker-daemon-1735744066225.json
> > /bin/sh: 1: sudo: not found
> > 
> >     at ChildProcess.exithandler (node:child_process:422:12)
> >     at ChildProcess.emit (node:events:517:28)
> >     at maybeClose (node:internal/child_process:1098:16)
> >     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
> >     at Process.callbackTrampoline (node:internal/async_hooks:128:17) {
> >   code: 127,
> >   killed: false,
> >   signal: null,
> >   cmd: "sudo sh -c '\n" +
> >     '\t\t\tcp /tmp/docker-daemon-1735744066225.json /etc/docker/daemon.json && \n' +
> >     '\t\t\tmkdir -p /etc/nvidia-container-runtime && \n' +
> >     '\t\t\tsed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml &&\n' +
> >     '\t\t\techo "swarm-resource = \\"DOCKER_RESOURCE_GPU\\"" >> /etc/nvidia-container-runtime/config.toml && \n' +
> >     '\t\t\tsystemctl daemon-reload && \n' +
> >     '\t\t\tsystemctl restart docker\n' +
> >     "\t\t' && rm /tmp/docker-daemon-1735744066225.json",
> >   stdout: '',
> >   stderr: '/bin/sh: 1: sudo: not found\n'
> > }
> > GPU Setup Error: Error: Failed to configure GPU support. Please ensure you have sudo privileges and try again.
> >     at f (/app/.next/server/chunks/8786.js:656:87)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at async d (/app/.next/server/chunks/8786.js:649:4782)
> >     at async /app/.next/server/chunks/500.js:14:81086
> >     at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:421:30)
> >     at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
> >     at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
> >     at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
> >     at async resolve (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
> >     at async inputToProcedureCall (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Version: v0.16.1
> 
> make sure you have root privileges, The error suggests that the system cannot find the `sudo` command

This command is supposed to be executed on the host machine which has docker engine, isn't it? It looks like it's being run inside a container.

**Comment by enryIT** [comment]
same problem @wizd wizd
running dockploy inside a privileged LXC container on proxmox. sudo is installed and working, docker is running with the root user.

`dokploy service`
```
docker service create \
  --name dokploy \
  --replicas 1 \
  --network dokploy-network \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/usr/bin/nvidia-container-runtime,target=/usr/bin/nvidia-container-runtime,readonly \
  --mount type=bind,source=/etc/docker/daemon.json,target=/etc/docker/daemon.json,readonly \
  --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
  --publish published=3000,target=3000,mode=host \
  --update-parallelism 1 \
  --update-order stop-first \
  -e ADVERTISE_ADDR=10.0.0.111 \
  -e NVIDIA_VISIBLE_DEVICES=all \
  --generic-resource "nvidia-gpu=1" \
  dokploy/dokploy:latest
```

`/etc/docker/daemon.json`
```
{
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    },
    "default-runtime": "nvidia",
    "node-generic-resources": [
      "nvidia-gpu=GPU-59aad624"
    ]
}
```

![Screenshot 2025-01-07 001624](https://github.com/user-attachments/assets/7e8aa75d-1d86-4307-b57b-45ed6a8a9bbc)

```
2025-01-06T23:12:13.626Z Setup failed: Error: Command failed: sudo sh -c '
2025-01-06T23:12:13.626Z cp /tmp/docker-daemon-1736205133621.json /etc/docker/daemon.json &&
2025-01-06T23:12:13.626Z mkdir -p /etc/nvidia-container-runtime &&
2025-01-06T23:12:13.626Z sed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml &&
2025-01-06T23:12:13.626Z echo "swarm-resource = \"DOCKER_RESOURCE_GPU\"" >> /etc/nvidia-container-runtime/config.toml &&
2025-01-06T23:12:13.626Z systemctl daemon-reload &&
2025-01-06T23:12:13.626Z systemctl restart docker
2025-01-06T23:12:13.626Z ' && rm /tmp/docker-daemon-1736205133621.json
2025-01-06T23:12:13.626Z /bin/sh: 1: sudo: not found
2025-01-06T23:12:13.626Z at ChildProcess.exithandler (node:child_process:422:12)
2025-01-06T23:12:13.626Z at ChildProcess.emit (node:events:517:28)
2025-01-06T23:12:13.626Z at maybeClose (node:internal/child_process:1098:16)
2025-01-06T23:12:13.626Z at Socket.<anonymous> (node:internal/child_process:450:11)
2025-01-06T23:12:13.626Z at Socket.emit (node:events:517:28)
2025-01-06T23:12:13.626Z at Pipe.<anonymous> (node:net:350:12)
2025-01-06T23:12:13.626Z at Pipe.callbackTrampoline (node:internal/async_hooks:128:17) {
2025-01-06T23:12:13.626Z code: 127,
2025-01-06T23:12:13.626Z killed: false,
2025-01-06T23:12:13.626Z signal: null,
2025-01-06T23:12:13.626Z cmd: "sudo sh -c '\n" +
2025-01-06T23:12:13.626Z '\t\t\tcp /tmp/docker-daemon-1736205133621.json /etc/docker/daemon.json && \n' +
2025-01-06T23:12:13.626Z '\t\t\tmkdir -p /etc/nvidia-container-runtime && \n' +
2025-01-06T23:12:13.626Z '\t\t\tsed -i "/swarm-resource/d" /etc/nvidia-container-runtime/config.toml &&\n' +
2025-01-06T23:12:13.626Z '\t\t\techo "swarm-resource = \\"DOCKER_RESOURCE_GPU\\"" >> /etc/nvidia-container-runtime/config.toml && \n' +
2025-01-06T23:12:13.626Z '\t\t\tsystemctl daemon-reload && \n' +
2025-01-06T23:12:13.626Z '\t\t\tsystemctl restart docker\n' +
2025-01-06T23:12:13.626Z "\t\t' && rm /tmp/docker-daemon-1736205133621.json",
2025-01-06T23:12:13.626Z stdout: '',
2025-01-06T23:12:13.626Z stderr: '/bin/sh: 1: sudo: not found\n'
2025-01-06T23:12:13.626Z }
2025-01-06T23:12:13.626Z GPU Setup Error: Error: Failed to configure GPU support. Please ensure you have sudo privileges and try again.
2025-01-06T23:12:13.626Z at f (/app/.next/server/chunks/8786.js:656:87)
2025-01-06T23:12:13.626Z at async d (/app/.next/server/chunks/8786.js:649:4782)
2025-01-06T23:12:13.626Z at async /app/.next/server/chunks/500.js:14:81086
2025-01-06T23:12:13.626Z at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:421:30)
2025-01-06T23:12:13.626Z at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
2025-01-06T23:12:13.626Z at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
2025-01-06T23:12:13.626Z at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
2025-01-06T23:12:13.626Z at async resolve (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
2025-01-06T23:12:13.626Z at async inputToProcedureCall (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
2025-01-06T23:12:13.626Z at async Promise.all (index 0)
```

**Comment by kadimon** [comment]
Hi! GPU Configuration func [checkSwarmResources](https://github.com/Dokploy/dokploy/blob/d66a5d55a3e05f004b90eb74ab47d23a0f996781/packages/server/src/utils/gpu-setup.ts#L128) make a search "DiscreteResourceSpec". But command return "NamedResourceSpec" . In result "Swarm GPU Support Not Enabled"  

![Image](https://github.com/user-attachments/assets/2e4d4d14-61ab-4831-b465-fc863b00a010)
![Image](https://github.com/user-attachments/assets/314035ee-6c82-4fe8-b9a5-c27c5845d5de)
